
#' Plot richness of interview codes over time
#'
#' The full definition of novel and duplicate codes is in [score_codes()].
#' Briefly, 'novel' codes are topics/ideas/concepts that were not mentioned in
#' previous interviews, whereas 'duplicate' codes are topics that other
#' interviews have discussed previously.
#'
#' This plot complements [plot_novelty()] by visualising the richness of each
#' interview in terms of novel and duplicate codes, in context with any
#' refinements to interview questions that were made (marked by stars underneath
#' each bar). By examining this plot together with their field notes, researchers
#' can get insight into the effects of their refinements and the richness of the
#' data.
#'
#' @param score_df (Dataframe) A dataframe of scored codes, as generated by [score_codes()].
#' @param refinements Either a list object generated by [import_field_notes()], or
#'    an Integer vector that lists when (in terms of interview
#'    sequence) refinements were made to the interview questions. For example,
#'    `c(10, 15)` means that interview questions were revised twice: First **before**
#'    the 10th interview, and then again **before** the 15th interview.
#'
#' @return A ggplot object.
#' @export
#'
#' @seealso [score_codes()], [import_field_notes()], [plot_novelty()], [save_last_plot()]
#'
#' @md
#' @importFrom ggplot2 .data
plot_richness <- function(score_df, refinements = integer(0)) {
    if ("field_notes" %in% class(refinements)) {
        refinements <- refinements$ref_points
    }

    plot_df <- reshape_for_plots(score_df, refinements)

    # 2023-07-05: For now, percentage (proportion of novel and duplicate codes
    # as a function of the total number of codes) is not exposed as an option
    # for this plot. We are happy to include it again if a good argument can
    # be made for its usefulness.
    percent <- FALSE
    if (isTRUE(percent)) {
        y_label = "Percent of interview codes"
        plot_df$measure <- plot_df$Proportion * 100
    } else {
        y_label = "Count of interview codes"
        plot_df$measure <- plot_df$n
    }

    annotate_refinements <- list(
        ggplot2::annotate(geom  = "text",
                          y     = rep(min(plot_df$measure) - stats::median(plot_df$measure) / 100 * 10, length(refinements)),
                          x     = refinements,
                          label = rep("\u2605", length(refinements)))
        )

    fill_clrs <- c(Duplicate = "gray90", Novel = "gray20")
    line_clrs <- c(Duplicate = "gray80", Novel = "gray10")

    ggplot2::ggplot(plot_df,
                    ggplot2::aes(x = .data$Interview, y = .data$measure,
                                 fill = .data$Code, colour = .data$Code,
                                 pattern = .data$Code, pattern_colour = .data$Code,
                                 pattern_fill = .data$Code)) +
        ggplot2::theme_bw() +
        ggplot2::theme(panel.grid.minor.x = ggplot2::element_blank(),
                       panel.grid.major.x = ggplot2::element_blank()) +
        ggpattern::geom_bar_pattern(stat = "identity", width = 0.7) +
        ggpattern::scale_pattern_manual(values = c(Duplicate = "stripe", Novel = "none")) +
        ggpattern::scale_pattern_colour_manual(values = fill_clrs) +
        ggpattern::scale_pattern_fill_manual(values = line_clrs) +
        ggplot2::scale_fill_manual(values = fill_clrs) +
        ggplot2::scale_colour_manual(values = line_clrs) +
        ggplot2::theme(legend.position = "top") +
        ggplot2::ylab(y_label) +
        ggplot2::xlab("Interview order\n(Refinements indicated by \u2605)") +
        annotate_refinements
}






