
#' Plot novelty of interview codes over time
#'
#' The 'novelty' of an interview is the proportion of codes that were mentioned
#' by this person, which were not previously mentioned by others.
#'
#' @param score_df (Dataframe) A dataframe of scored codes, as generated by [score_codes()].
#' @param refinements (Integer) A vector that lists when (in terms of interview
#'    sequence) refinements were made to the interview questions. For example,
#'    `c(10, 15)` means that interview questions were revised twice: First **before**
#'    the 10th interview, and then again **before** the 15th interview.
#' @param method (Character) Method for smoothing that will be passed to [ggplot2::stat_smooth()].
#' @param formula (Formula) Formula for smoothing that will be passed to [ggplot2::stat_smooth()].
#'
#' @return A ggplot object.
#' @export
#'
#' @md
plot_novelty <- function(score_df, refinements = integer(0), method = "lm", formula = y ~ poly(x, 8)) {
    plot_df <- reshape_for_plots(score_df, refinements)

    annotate_refinements <- list(
        ggplot2::geom_vline(xintercept = refinements,
                            linetype   = "dashed",
                            colour     = "blue"))

    ggplot2::ggplot(plot_df,
                    ggplot2::aes(x = itvw_seq, y = prop_novel)) +
        ggplot2::theme_bw() +
        ggplot2::theme(panel.grid.minor = ggplot2::element_blank()) +
        ggplot2::geom_line(stat    = "smooth",
                           method  = method,
                           formula = formula,
                           alpha   = 0.5,
                           se      = FALSE) +
        ggplot2::geom_point() +
        ggplot2::ylab("Proportion of novel codes") +
        ggplot2::xlab("Interview sequence number") +
        annotate_refinements
}

