
#' Plot cumulative sum of novel codes over time
#'
#' In this plot, the count of novel codes is cumulatively summed over all
#' interviews. Plateaus in this line could suggest a stoppin point for further
#' interviews, unless refinements to the interview questions introduce more
#' novel codes.
#'
#' @param score_df (Dataframe) A dataframe of scored codes, as generated by [score_codes()].
#' @param refinements (Integer) A vector that lists when (in terms of interview
#'    sequence) refinements were made to the interview questions. For example,
#'    `c(10, 15)` means that interview questions were revised twice: First **before**
#'    the 10th interview, and then again **before** the 15th interview.
#' @param method (Character) Method for smoothing that will be passed to [ggplot2::stat_smooth()].
#' @param formula (Formula) Formula for smoothing that will be passed to [ggplot2::stat_smooth()].
#'
#' @return A ggplot object.
#' @export
#'
#' @md
plot_novel_cumsum <- function(score_df, refinements = integer(0)) {
    plot_df <- reshape_for_plots(score_df, refinements)

    annotate_refinements <- list(
        ggplot2::geom_vline(xintercept = refinements,
                            linetype   = "dashed",
                            colour     = "blue"))

    ggplot2::ggplot(plot_df,
                    ggplot2::aes(x = itvw_seq, y = cumsum_novel, group = refinement_group)) +
        ggplot2::theme_bw() +
        ggplot2::theme(panel.grid.minor = ggplot2::element_blank()) +
        ggplot2::geom_line(alpha = 0.5) +
        ggplot2::geom_point() +
        ggplot2::ylab("Cumulative sum of novel codes") +
        ggplot2::xlab("Interview sequence number") +
        annotate_refinements
}
