
#' Reshape score matrix for ggplot2.
#'
#' @param score_df (Dataframe) A scored code matrix as generated by [score_codes()].
#' @param refinements (Integer) A vector that lists when (in terms of interview
#'    sequence) refinements were made to the interview questions. For example,
#'    `c(10, 15)` means that interview questions were revised twice: First **before**
#'    the 10th interview, and then again **before** the 15th interview.
#'
#' @return A dataframe.
#'
#' @md
reshape_for_plots <- function(score_df, refinements = integer(0)) {
    plot_df <- score_df

    plot_df$refinement_group <- cut(plot_df$itvw_seq,
                                    breaks = c(-Inf, refinements, Inf),
                                    right = FALSE,
                                    include.lowest = TRUE)

    return(plot_df)
}

